import Product from "./Products";

export const dumbProducts: Product[] = [
  {
    id: "1",
    name: "Camisa Social Azul",
    brand: "Zara",
    price: 79.99,
    description: "Camisa social azul perfeita para o trabalho e eventos formais.",
    imageUrl: "/assets/img/dumbProduct.jpg",
  },
  {
    id: "2",
    name: "T-Shirt Algodão Orgânico",
    brand: "H&M",
    price: 29.99,
    description: "Confortável e sustentável, feita com algodão 100% orgânico.",
    imageUrl: "/assets/img/dumbProduct.jpg",
  },
  {
    id: "3",
    name: "Calça Jeans Slim Fit",
    brand: "Levi's",
    price: 89.99,
    description: "Calça jeans versátil com corte slim fit para um look moderno.",
    imageUrl: "/assets/img/dumbProduct.jpg",
  },
  {
    id: "4",
    name: "Blazer Moderno Preto",
    brand: "Armani",
    price: 299.99,
    description: "Blazer preto elegante para um visual sofisticado.",
    imageUrl: "/assets/img/dumbProduct.jpg",
  },
  {
    id: "5",
    name: "Sapatênis de Couro",
    brand: "Polo Ralph Lauren",
    price: 119.99,
    description: "Sapatênis de couro confortável, ideal para o dia a dia.",
    imageUrl: "/assets/img/dumbProduct.jpg",
  },
  {
    id: "6",
    name: "Bermuda Chino",
    brand: "Brooksfield",
    price: 59.99,
    description: "Bermuda chino leve, perfeita para um dia quente.",
    imageUrl: "/assets/img/dumbProduct.jpg",
  },
  {
    id: "7",
    name: "Polo Clássica",
    brand: "Lacoste",
    price: 85.0,
    description: "Camisa polo clássica, um item indispensável no guarda-roupa.",
    imageUrl: "/assets/img/dumbProduct.jpg",
  },
  {
    id: "8",
    name: "Moletom com Capuz",
    brand: "Nike",
    price: 69.99,
    description: "Moletom com capuz para um look casual e confortável.",
    imageUrl: "/assets/img/dumbProduct.jpg",
  },
  {
    id: "9",
    name: "Jaqueta de Couro",
    brand: "Diesel",
    price: 459.99,
    description: "Jaqueta de couro estilo motoqueiro, robusta e estilosa.",
    imageUrl: "/assets/img/dumbProduct.jpg",
  },
  {
    id: "10",
    name: "Relógio Smartwatch",
    brand: "Apple",
    price: 399.99,
    description: "Smartwatch com diversas funcionalidades para o dia a dia.",
    imageUrl: "../assets/img/dumbProduct.jpg",
  },
];

export default dumbProducts;
